"""Script 8: predictions.csv -> SQL insert file (v1.0).

Reads:  data/predictions/predictions.csv
Writes: output/sql/insert_predictions.sql

Paste the output into the Supabase SQL editor AFTER migration 024
(unique index on route_id + prediction_date) — ON CONFLICT DO NOTHING
then makes re-pastes no-ops instead of duplicates.

confidence_score and weather_id ship as NULL (no calibrated
confidence from the model; weather rows are per-port history, not
linked to predictions).
"""

import pandas as pd

from src.utils import ensure_dir, get_project_root

TABLE = "demand_predictions"
COLUMNS = [
    "prediction_date", "day_of_week", "hour_of_day", "is_weekend",
    "is_holiday", "previous_demand", "avg_demand_last_7_days",
    "avg_demand_last_30_days", "predicted_passengers",
    "confidence_score", "weather_id", "route_id",
]


def literal(value) -> str:
    """Python/pandas value -> SQL literal."""
    if value is None or pd.isna(value):
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int,)):
        return str(value)
    if isinstance(value, float):
        return str(int(value)) if value.is_integer() else str(round(value, 2))
    text = str(value).replace("'", "''")
    return f"'{text}'"


def main() -> None:
    """Render every prediction row as one idempotent INSERT."""
    root = get_project_root()
    path = root / "data" / "predictions" / "predictions.csv"
    df = pd.read_csv(path)

    out_path = root / "output" / "sql" / "insert_predictions.sql"
    ensure_dir(out_path.parent)

    if df.empty:
        out_path.write_text(
            "-- No predictions — re-run Scripts 1-7 first.\n", encoding="utf-8"
        )
        print("predictions.csv is empty — wrote a comment-only SQL file")
        return

    rows = []
    for r in df.itertuples(index=False):
        values = [
            literal(r.prediction_date),
            literal(r.day_of_week),
            str(int(r.hour_of_day)),
            literal(bool(r.is_weekend)),
            literal(bool(r.is_holiday)),
            str(int(r.previous_demand)),
            literal(float(r.avg_demand_last_7_days)),
            literal(float(r.avg_demand_last_30_days)),
            str(int(r.predicted_passengers)),
            "NULL",  # confidence_score
            "NULL",  # weather_id
            literal(r.route_id),
        ]
        rows.append("(" + ", ".join(values) + ")")

    sql = (
        f"-- BangkaGo ML predictions ({len(df)} rows, "
        f"{df['prediction_date'].min()} .. {df['prediction_date'].max()})\n"
        f"-- Generated by ml/src/export_sql.py — requires migration 024.\n"
        f"INSERT INTO {TABLE} ({', '.join(COLUMNS)}) VALUES\n"
        + ",\n".join(rows)
        + "\nON CONFLICT DO NOTHING;\n"
    )
    out_path.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(df)} INSERT rows to {out_path}")


if __name__ == "__main__":
    main()
